version: '3.9'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  kittygram:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: arthursokolov/kittygram_backend
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/backend_static/
      - media_volume:/app/backend_media/

  frontend:
    image: arthursokolov/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: arthursokolov/kittygram_gateway
    restart: always
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/static/
      - media_volume:/media/
