version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  kittygram:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    restart: always
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/backend_media/

  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: ./nginx/
    restart: always
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/media/
